version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${database}
    ports:
      - "5432:5432"

  initdb:
    image: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    depends_on:
      - db

volumes:
  db-data: